CREATE DATABASE IF NOT EXISTS web_task
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE web_task;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age TINYINT UNSIGNED NOT NULL,
    status TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (name, age, status)
VALUES
    ('Ahmed', 23, 0),
    ('Sara', 21, 1);